### ISSUE TITLE
Jest tests fail on Jenkins

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/garnet#45]
Bug

### Input Code

```js
NODE_ENV=test jest -u
```

### Garnet Configuration (etc/config.yaml)

```yaml
log_file: log/garnet.log
log_level: info
agent_cache_directory: cache
language: en
interval: 100
agent_subprocesses: 10
listen_address: 0.0.0.0
bind_port: 5000
api_server_name: 0.0.0.0
api_server_port: 6000
api_server_https: False
api_server_uri: /infoset/api/v1
```

### Expected Behavior

Tests to pass
### Current Behavior

Tests to pass
### Possible Solution

Add in `.transform` folder and jest preprocessor

### Your Environment

| software         | version(s)
| ---------------- | -------
| garnet           |  1.0.0
| node             |  8.1.3
| npm              | 5.0..2
| Operating System | Arch linux
