### ISSUE TITLE
npm start isn't allowing me to launch garnet.

### ISSUE THREAD

**Issue by Mardii-D-King** [PalisadoesFoundation/garnet#47]
Choose one: is this a bug report or feature request?

Bug Report

When trying to launch this application with npm start it failed to execute.

### Input Code

npm start

```js
var your => (code) => here;
```

### Garnet Configuration (etc/config.yaml)

```yaml
{
  your
  - config
  - here
log_file: log/garnet.log
log_level: info
agent_cache_directory: cache
language: en
interval: 100
agent_subprocesses: 10
listen_address: 0.0.0.0
bind_port: 5000
api_server_name: 0.0.0.0
api_server_port: 6000
api_server_https: False
api_server_uri: /infoset/api/v1

agents:
    - agent_name: _garnet
      agent_enabled: True
      agent_filename: bin/agents/_garnet.py
      monitor_agent_pid: True

    - agent_name: linux
      agent_enabled: False
      agent_filename: bin/agents/linux.py
      agent_port: 5001
      monitor_agent_pid: True
      agent_devicenames:
        - 192.168.1.234

    - agent_name: remote_linux_active
      agent_enabled: False
      agent_filename: bin/agents/remote_linux_active.py

    - agent_name: remote_linux_passive
      agent_enabled: False
      agent_filename: bin/agents/remote_linux_passive.py

}
```

### Expected Behavior

Infoset should have run and garnet would be served on localhost to view the UI

### Current Behavior

I got this error 

`npm ERR! path /home/mardii/Documents/Calico/garnet/static/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/mardii/Documents/Calico/garnet/static/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mardii/.npm/_logs/2017-06-29T22_27_19_884Z-debug.log`

### Context

I am unable to run garnet

### Your Environment

| software         | version(s)
| ---------------- | -------
| garnet           |  Not sure
| node             | 8.1.2
| npm              | 5.0.4
| Operating System | Arch Linux
